version: "2.0"
services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
# networks:
#   default:
#     external:
#       name: slots-calculations-microservice_default
